version: "3"

services:
  app:
    build: .
    image: mazzolino/shepherd
    environment:
      FILTER_SERVICES: "name=amm"
      WITH_REGISTRY_AUTH: "true"
      SLEEP_TIME: "30s"
      IMAGE_AUTOCLEAN_LIMIT: "3"
      REGISTRY_HOST: "https://index.docker.io/v1/"
      REGISTRY_USERNAME: "jerradpatch"
      REGISTRY_PASSWORD: "Darrej12"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager


