#!/bin/bash
set -euo pipefail

server_version() {
  docker version -f "{{.Server.Version}}"
}

update_services() {
  local blacklist="$1"
  local supports_detach_option=$2
  local detach_option=""
  [ $supports_detach_option = true ] && detach_option="--detach=false"

  for service in $(IFS="\n" docker service ls --quiet); do
    local name image_with_digest image
    name="$(docker service inspect "$service" -f '{{.Spec.Name}}')"
    if [[ " $blacklist " != *" $name "* ]]; then
      image_with_digest="$(docker service inspect "$service" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')"
      image=$(echo "$image_with_digest" | cut -d@ -f1)
      echo "Updating service $name with image $image"
      docker service update --with-registry-auth "$service" $detach_option --image="$image" > /dev/null
    fi
  done
}

main() {
  local blacklist sleep_time supports_detach_option registry_host registry_username registry_password
  blacklist="${BLACKLIST_SERVICES:-}"
  sleep_time="${SLEEP_TIME:-5m}"
  registry_host="${REGISTRY_HOST:-}"
  registry_username="${REGISTRY_USERNAME:-}"
  registry_password="${REGISTRY_PASSWORD:-}"

  supports_detach_option=false
  if [[ "$(server_version)" > "17.05" ]]; then
    supports_detach_option=true
    echo "Enabling synchronous service updates"
  else
    supports_detach_option=false
  fi

  [[ "$registry_host" != "" ]] && echo "Using private registry at: $registry_username@$registry_host" && docker login --username $registry_username --password $registry_password $registry_host
  
  [[ "$blacklist" != "" ]] && echo "Excluding services: $blacklist"

  while true; do
    update_services "$blacklist" "$supports_detach_option"
    echo "Sleeping $sleep_time before next update"
    sleep "$sleep_time"
  done
}

main "$@"
